### PR TITLE
Use semantic model of invocation syntax node to prevent S3241 c…

### LINKED ISSUE #3086: S3241 UnusedReturnValue throws AD0001 System.ArgumentException
### Description

Dnspy https://cirrus-ci.com/task/5443779553394688 

```
   CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedReturnValue' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'. [C:\Project\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet.Mono\dnSpy.Debugger.DotNet.Mono.csproj]
```

Nhibernate https://cirrus-ci.com/task/4986382716239872

```
   CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedReturnValue' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'. [C:\Project\src\NHibernate\NHibernate.csproj]
    CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedReturnValue' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'. [C:\Project\src\NHibernate\NHibernate.csproj]
    CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedReturnValue' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'. [C:\Project\src\NHibernate\NHibernate.csproj]
        13325 Warning(s)
```

### PR DESCRIPTION
**Pull request by christophe-zurn-sonarsource**
fix #3086

### CODE REVIEW

**Comment by costin-zaharia-sonarsource** [comment]
Would it be possible to add a test which verifies that the issue is fixed?

**Comment by christophe-zurn-sonarsource** [comment]
@costin-zaharia-sonarsource For some reason, I cannot make a small reproducer. I found the code that raises the issue in the source project `SmartStoreNet`, but when I try to add a small reproducer, it works correctly. I think it's related to compilation and how semantic models are divided when project becomes big, with a small reproducer, everything is available in the same semantic model.
But I tested locally with the `SmartStoreNet` project, and this fixes the issue

**Comment by andrei-epure-sonarsource** [comment]
why is S3241 crashing?
there is no ticket and no mention of an error - why is this needed?

**Comment by christophe-zurn-sonarsource** [comment]
@andrei-epure-sonarsource Yes, it is related to #3086. This is the result of peach investigation

**Pull request merged**
