### PR TITLE
S5944: Use explicit return statements

### PR DESCRIPTION
**Pull request by Corniel**
Looking back to some old work, I noticed I never pushed #2159.
As everything is already [documented](https://jira.sonarsource.com/browse/RSPEC-5944), it should be a walk in the park.

### CODE REVIEW

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Corniel,

Thank you for the contribution. As this is a new rule, we need to modify more files. Can you please rebase on latest master and cherry pick the scaffolding I created for you in this branch https://github.com/SonarSource/sonar-dotnet/tree/Pavel/Corniel-S5944-Return ?

Thanks

**Comment by Corniel** [comment]
Hmm, not sure if this was as intended.  (I hate rebase)

**Comment by pavel-mikula-sonarsource** [comment]
The history went wrong here. Seems like the scaffolding is on a wrong timeline. To get it done in a simple way, I suggest to:
- checkout our latest master
- create new branch from it
- cherry pick my scaffolding to your new branch
- cherry pick your implementation to your new branch
- update branch of this PR to the new one

**Comment by Corniel** [comment]
Redone in a new branch.

**Pull request closed without merging**
