### PR TITLE
Remove analyzer maven artifacts

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
I have no idea what I'm doing. 

Let's give this a try. It can either:
* break something that is not tested - what did I break?
* remove unused and confusing configuration

My best guess is that it was supposed to publish artifacts there were downloaded by #4486.

By deleting it, we simplify structure of the repository. And make the `Bump version to 8.xx` easier to review in terms of understanding 
Example: see https://github.com/SonarSource/sonar-dotnet/pull/6107/files - we review those 5 changed files every time, I doubt anyone really knows what these 5 files do and :why: we change them.

### CODE REVIEW

**Comment by andrei-epure-sonarsource** [comment]
[process] can you open a ticket mentioning the confusion problem (which I agree with), just to have a ticket to refer to later on?

**Comment by pavel-mikula-sonarsource** [comment]
It's a non-functional tooling improvement (AFAICT), I would not pollute the issue list with a duplicate record (PR = Issue+code). At this stage, I don't even know if we can do it or what I'm doing.

**Comment by andrei-epure-sonarsource** [comment]
Makes sense, @pavel-mikula-sonarsource , this is actually related to #4486 as you've mentioned.

Some checks I did:
- indeed, a "RuleDocGenerator" used to be shipped as a nuget to https://repox.jfrog.io/ui/native/sonarsource-public-releases/org/sonarsource/dotnet/SonarAnalyzer.RuleDocGenerator.CSharp/8.0.0.9566/
- analyzers/sonaranalyzer-maven-artifacts/SonarAnalyzer.CSharp/pom.xml and the VB equivalent were creating NuGet packages with `file-SonarAnalyzer.CSharp` (however I cannot file this name on the repox; there it was published without the `file-` prefix) https://repox.jfrog.io/ui/native/sonarsource-public-releases/org/sonarsource/dotnet/SonarAnalyzer.CSharp/8.0.0.9566/

This seems just an artefact which should have been removed in #4486.

Thanks for the cleanup.

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM

not merging now (code freeze for release)

**Pull request merged**
