### PR TITLE
Split SyntaxNodeExtensions in multiple files

### PR DESCRIPTION
**Pull request by Tim-Pohlmann**
`SonarAnalyzer.CSharp.Extensions.SyntaxNodeExtensions.cs` and `SonarAnalyzer.UnitTest.Extensions.SyntaxNodeExtensionsTests.cs` are getting very long. Splitting them up into multiple files will help keeping them maintainable.

### CODE REVIEW

**Comment by pavel-mikula-sonarsource** [comment]
@Tim-Pohlmann this PR doesn't make much sense as it is. It looks like it was created form a wrong branch

**Comment by Tim-Pohlmann** [comment]
> 

> @Tim-Pohlmann this PR doesn't make much sense as it is. It looks like it was created form a wrong branch
@pavel-mikula-sonarsource This PR is an empty place holder as a reminder for me. It's based on one of Martin's branches because I want to do the refactor including his changes. My intention was to rebase it after the other commit got merged to master. I didn't realize it would look like this in GitHub, when I was creating it. This doesn't seem to be the best way to do this. Should I just delete it and use a different way of keeping track of what still needs to be done?

**Comment by pavel-mikula-sonarsource** [comment]
PR isn't a good tool to represent a placeholder or a ToDo task.
You could have:
- Plan A: create a branch from Martin's one, squash all commits, add your changes already, even ask for a review, wait for his PR to be merged, rebase, merge
- Plan B: create a branch from Martin's one, add your changes already, create Draft PR, target his branch, wait for it to be merged, rebase,  merge - this would be more painful as Martin tends to create too many commits
- Plan C: Just add a ToDo into your sprint notes

I'd personally go for plan A or C.

**Comment by Tim-Pohlmann** [comment]
@pavel-mikula-sonarsource alright, thanks for the helpful suggestions. I'll close this one and make a new one later.

**Pull request closed without merging**
