### PR TITLE
New Rule S5842: Regular expressions should not match an empty string

### PR DESCRIPTION
**Pull request by Corniel**
Implementing [RSPEC-5842](https://rules.sonarsource.com/java/RSPEC-5842).

[RSPEC-5842]: https://sonarsource.atlassian.net/browse/RSPEC-5842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Corniel** [comment]
@pavel-mikula-sonarsource The `[GeneratedRegex]` has not been added yet. I tried some things to get the test cases running, but so far, without success. Did someone already try that?

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
I don't think we can implement S5842 one with simple string operations.

https://sonarsource.github.io/rspec/#/rspec/S5842
From reading the rule specification, this one is to meant to avoid more complex regexes with repetition that would match en empty string. That is not same as the "empty" string.

I don't think we have a rule to say that regex pattern should not be empty.

**Comment by Corniel** [comment]
> I don't think we have a rule to say that regex pattern should not be empty.

Hmm, I missread this one. I was - obviously - searching for rules that could be implemented without building up a full regex tree. That being said, it might already be benefitial to investigate how to test rules that should apply on ``[GeneratedRegex]`?!

**Comment by pavel-mikula-sonarsource** [comment]
There are 2 steps needed to make the `GeneratedRegex` work:

First is to add a reference to `System.Text.RegularExpressions 7.0.0`. This can be done in `CoreMetadataReference` class like this:
```
internal static MetadataReference SystemTextRegularExpressions { get; } = CreateReference("System.Text.RegularExpressions.dll");
```
and this then needs to be used in `MetadataReferenceFacade` for .NET Builds only.

Second is to plug in `System.Text.RegularExpressions.Generator.dll` source generator. We didn't try to use source generators for our in-memory compilation in UTs yet. I guess we'd need to plug it in as analyzer using `.AddAnalyzer()` somehow but we didn't test this.

It's probably easier not to write UT for this and write IT instead. It means add new file into this project
https://github.com/SonarSource/sonar-dotnet/tree/master/analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/Net7
and run this script from `analyzer/its` directory
```
.\regression-test.ps1 -ruleId Sxxxx -project ManuallyAddedNoncompliantIssues.CS
```

**Comment by pavel-mikula-sonarsource** [comment]
I'll close this PR as this rule will not make it further. 

If I remember correctly, there was one more rule possible. In case you'll do it, please create a language-specific abstract rule base class that will deal with the common registration in `Initialize` method.

**Pull request closed without merging**
