### PR TITLE
Update contributing-analyzer.md

### PR DESCRIPTION
**Pull request by Tim-Pohlmann**
Added the requirement to install .NET SDK 6.0.

### CODE REVIEW

**Review by martin-strecker-sonarsource — APPROVED** [review]
LGTM @pavel-mikula-sonarsource for merging

**Comment by pavel-mikula-sonarsource** [comment]
Nope, targets frozen master, needs to wait in the queue of "Review approved" column

**Comment by Tim-Pohlmann** [comment]
@pavel-mikula-sonarsource can this be merged now?

**Comment by pavel-mikula-sonarsource** [comment]
@Tim-Pohlmann It's as green as it could be and master is not frozen anymore => :shipit: 

My help is not needed.

**Pull request merged**
