### PR TITLE
Update rspec before release

### PR DESCRIPTION
**Pull request by costin-zaharia-sonarsource**

### CODE REVIEW

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM (I looked out of curiosity)

**Review by pavel-mikula-sonarsource — COMMENTED** [review]
S1313 has a description update that we can use. While skipping the "Exceptions" section if not implemented.

**Review by pavel-mikula-sonarsource — COMMENTED** [review]
What's the situation with S2228 deprecation? Rule api generates note that's not a part of this PR

**Review by pavel-mikula-sonarsource — COMMENTED** [review]
S3925 (that's not part of this PR) seems to have some formatting issue in JIRA and rule-api generates bad list. Can you fix the specification?

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
~~VB.NET / S1821 description should be updated. Rule is implemented, I've fixed missing examples in the RSPEC recently~~

I take this one back, it's there. I somehow overlooked it.

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM. I left 3 comments/questions above to clarify situation.

**Comment by costin-zaharia-sonarsource** [comment]
> What's the situation with S2228 deprecation? Rule api generates note that's not a part of this PR

We clarified this offline, the S2228 is already updated on master by https://github.com/SonarSource/sonar-dotnet/pull/3775

**Pull request merged**
