### PR TITLE
Fail build when UTs fail

### LINKED ISSUE #3686: AZP - build should fail when UTs fail
The UTs are ran via a powershell command: https://github.com/SonarSource/sonar-dotnet/blob/master/azure-pipelines.yml#L226

The problem is that when UTs fail, we don't check the error code. Only if the last command will fail, the job will fail.

We already have the powershell command to do that in build-utils.ps1 `Test-ExitCode`

```
    if ((-not $?) -or ($lastexitcode -ne 0)) {
        throw $errorMessage
    }
```

### PR DESCRIPTION
**Pull request by andrei-epure-sonarsource**
Fixes #3686

please **squash**

### CODE REVIEW

**Comment by andrei-epure-sonarsource** [comment]
build for commit 
83f45dc  is  https://sonarsource.visualstudio.com/DotNetTeam%20Project/_build/results?buildId=23312&view=results

**Comment by andrei-epure-sonarsource** [comment]
build for commit 588c009 is https://sonarsource.visualstudio.com/DotNetTeam%20Project/_build/results?buildId=23313&view=results

**Comment by andrei-epure-sonarsource** [comment]
build for c7dd5b5 is https://sonarsource.visualstudio.com/DotNetTeam%20Project/_build/results?buildId=23314&view=results

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM!

**Comment by costin-zaharia-sonarsource** [comment]
> /azp run Sonar.Net.External

It seems that I forgot to remove NuGet caching from `Sonar.Net.External` after I deleted the lock files. I can do this in a separate PR.

**Pull request merged**
