### PR TITLE
Merge Corniel's feature branch

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
DO NOT SQUASH.

Each commit was already reviewed in its own PR, see the commit history.

 cc @Corniel

### CODE REVIEW

**Comment by pavel-mikula-sonarsource** [comment]
Coverage is low due to some renaming in SE. Now it's a good time to merge this, as all SE files will be moved in the current sprint.

**Comment by costin-zaharia-sonarsource** [comment]
@pavel-mikula-sonarsource, will you handle the validation?

**Comment by pavel-mikula-sonarsource** [comment]
> @pavel-mikula-sonarsource, will you handle the validation?

Yes

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
