### PR TITLE
Fix S6354 FP: Do not report on XML crefs and nameof

### LINKED ISSUE #7504: Fix S6354 FP: Do not report on XML crefs and nameof
S6354: There is no reason why the XML cref or a nameof expression could not have a reference to DateTime.Now or any of its variants.

### PR DESCRIPTION
**Pull request by Corniel**
Fixes #7504

### CODE REVIEW

**Review by Tim-Pohlmann — CHANGES_REQUESTED** [review]
Hello @Corniel; thanks for handling this.
The code looks very good, but can you please update the ITs?

**Comment by Corniel** [comment]
> Hello @Corniel; thanks for handling this. The code looks very good, but can you please update the ITs?

I had troubles in the past running those, due to the required configuration that I do not want to setup on my developer machine. I someone else can do that?

**Comment by Corniel** [comment]
@Tim-Pohlmann you still have it marked as changes required. ;)

**Pull request merged**
