### PR TITLE
bump s4net version to 5.7.2

### PR DESCRIPTION
**Pull request by andrei-epure-sonarsource**
as part of our release process: https://xtranet-sonarsource.atlassian.net/wiki/spaces/SSG/pages/1181769/Scanner+for+.NET+Release+Process

we want to be using the latest S4NET version in all our ITs

### CODE REVIEW

**Comment by martin-strecker-sonarsource** [comment]
[educational] 
> as part of our release process

I couldn't find this part of the process in the document. Can you tell which part of the document triggered this PR?

**Review by martin-strecker-sonarsource — APPROVED** [review]

**Comment by martin-strecker-sonarsource** [comment]
LGTM.

**Comment by martin-strecker-sonarsource** [comment]
(I'm not sure if I should merge this PR already. To be on the safe side, I'll leave this to you).

**Comment by andrei-epure-sonarsource** [comment]
@martin-strecker-sonarsource thanks!

> I couldn't find this part of the process in the document. Can you tell which part of the document triggered this PR?

it's  `step 14: Create PRs to update the S4NET version in our safety nets`

> (I'm not sure if I should merge this PR already. To be on the safe side, I'll leave this to you).

Yes, it's safe. Step 6 (the actual release scripts) do the release on github, chocolatey and nuget gallery. So after step 6, the scanner is already out in the wild. So we should use it in all our integration tests, because that's the released version.

Steps 14-15 are necessary to improve our confidence before updating the S4NET version inside our Azure DevOps Extension, because users cannot control the underlying version of the scanner.

**Pull request merged**
