### PR TITLE
UtilityAnalyzer: Annotate with performance sensitive

### PR DESCRIPTION
**Pull request by martin-strecker-sonarsource**
The code smells are due to this bug:
https://github.com/dotnet/roslyn-analyzers/issues/6851

### CODE REVIEW

**Comment by costin-zaharia-sonarsource** [comment]
Shouldn't we disable [HAA0502](https://sonarcloud.io/organizations/sonarsource/rules?open=external_roslyn%3AHAA0502&rule_key=external_roslyn%3AHAA0502) rule? It seems very noisy.

**Comment by martin-strecker-sonarsource** [comment]
I would keep it (it is actually a good rule after all) and fix the FP in the analyzer instead. It must be somewhere here:
https://github.com/dotnet/roslyn-analyzers/blob/47c7281a7f5d6e2aaff186499d2194fdb86adb4d/src/PerformanceSensitiveAnalyzers/Core/ExplicitAllocationAnalyzer.cs#L90

and shouldn't be difficult.

**Comment by costin-zaharia-sonarsource** [comment]
Ok. Please mark then all the code smells as false positives.

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
