### PR TITLE
S1144, S4487: Ignore entity framework migration files

### LINKED ISSUE #2474: Analysis of Entity Framework migration files never completes
### Description
Analysis of large files never completes.
See https://github.com/SonarSource/sonar-scanner-msbuild/issues/590

### TODO
Investigate which analysis rules are causing the issue. UPDATE: S1144 and S4487 (same implementation class)
~~Potentially related to https://github.com/SonarSource/sonar-dotnet/issues/2429, which relates to utility rules taking too long. However, the repro here is more extreme - effectively the build never completes and the user has to kill it.~~

### Repro
1. clone https://github.com/ksitarek/sonarscannersample
2. build the project using the sonar-dotnet analyzers

Note: the bug repros with just the file `20181005212624_InitialCreate.cs` in project `vtb.Warehouse.Data`

### Expected
The build completes successfully in a reasonable time.

### Actual
The build does not end.

### Known workarounds
A) Exclude the project from analysis by adding the `SonarQubeExclude` property:

```
  <PropertyGroup>
    <SonarQubeExclude>true</SonarQubeExclude> 
  </PropertyGroup>
```

or 

B) Disable rule S1144 (`Unused private types or members should be removed`) and rule S4487 (`Unread "private" fields should be removed`) (both implemented by `UnusedPrivateMember.cs`.

### Notes
The problematic project in the sample project is `vtb.Warehouse.Data`. This is an Entity Framework project that contains migrations, all of which are several thousand lines long.

### PR DESCRIPTION
**Pull request by costin-zaharia-sonarsource**
Fixes #2474

### CODE REVIEW

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
I'd like to add a unit test to see it in action 🙂

**Comment by costin-zaharia-sonarsource** [comment]
> I'd like to add a unit test to see it in action 🙂

I don't understand what do you mean 😄

**Comment by pavel-mikula-sonarsource** [comment]
We already have a performance test that's implemented by ignoring Guid. But this PR says that everything inside Migration class is ignored. And we don't have a test for that.

I'd like to have a class inheriting Migration with few private unused lines (like in TestCases/UnusedPrivateMember.cs) with comments that it's compliant due to ignored type.

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
