### PR TITLE
Disable IDE0057

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
This asks to replace
```
var filePath = Location.Uri.Substring(Location.Uri.IndexOf("analyzers/its"));
```
with fairly unreadable
```
var filepath = Location.Uri[Location.Uri.IndexOf("analyzers/its")..];
```

### CODE REVIEW

**Review by gregory-paidis-sonarsource — COMMENTED** [review]
One question about this:
I remember that we generally want to adopt new C# language features.
There is a non-zero chance that we are just not used to the python-esque range operator syntax and it feels confusing, as it is very new.
Shouldn't we raise this to the rest of the team?

**Comment by pavel-mikula-sonarsource** [comment]
Range and index operators are C# 8 and they are not new in the language. We don't use them, because they make the code way harder to read.

While this doesn't prevent using them (good luck with getting such PR approved), it stops the over-usage inflicted by IDE

**Comment by gregory-paidis-sonarsource** [comment]
Ah I confused it with the spread operator in thw new collection literals.

**Review by gregory-paidis-sonarsource — APPROVED** [review]
LGTM

**Comment by Tim-Pohlmann** [comment]
> We don't use them, because they make the code way harder to read.

Is there any documentation on this guideline and on how we came to such a decision?

**Comment by pavel-mikula-sonarsource** [comment]
It's written in the C# spec. `value = value[^2..];` is simply a NO-GO from a readability point of view.

This PR doesn't forbid you to try that. It only prevents VS from oversuggesting to make that mistake.

**Pull request merged**
