### PR TITLE
Rename NodeAndSemanticModel to NodeAndModel

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**

### CODE REVIEW

**Comment by Corniel** [comment]
I Would argue that the name `NodeWithModel` better descibes what is contains; the SytnaxNode with the semantic model it is part of.

**Comment by pavel-mikula-sonarsource** [comment]
@Corniel There's also `NodeSymbolAndSemanticModel` mechanically renamed to `NodeSymbolAndModel` in this PR. How would that be named using the `With`?

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM! Just one small comment.

**Comment by pavel-mikula-sonarsource** [comment]
They both look quite equal. We'll keep them with `And` for now as I was dealing with the `Semantic` part.

**Pull request merged**
