### PR TITLE
FP 2259: Respect ! (null-forgiving) operator

### LINKED ISSUE #6082: Improve S2259: Respect ! (null-forgiving) operator
The [bang operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving) can be used to declare an expression as being not null. S2259 should not raise for expressions annotated with this operator.

```cs
#nullable enable
var o = null;
o!.ToString(); // Do not raise S2259 here
```

### PR DESCRIPTION
**Pull request by martin-strecker-sonarsource**
Fixes #6082

### CODE REVIEW

**Comment by martin-strecker-sonarsource** [comment]
@pavel-mikula-sonarsource this is how we could handle the [bang operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving).

Instead of a dedicated check, we could also integrate the logic into `RoslynSymbolicExecution.ProcessOperation`.

Can you have a brief look and give your advice on how to integrate it best?

**Comment by pavel-mikula-sonarsource** [comment]
I didn't see anything in the CFG itself => we have to use syntax => we should do it in `SonarAnalyzer.CSharp` => let's do it `NullPointerDereference.cs`. With some virtual `ShouldReport(c.Node)` that would have override in C# that would not report on the bang

**Comment by martin-strecker-sonarsource** [comment]
> I didn't see anything in the CFG itself

The info is there, but it is not as straightforward to get there:

```cs
#nullable enable
public class C {
    public void M() {
        object? o = null;
        o!.ToString(); // IdentifierNameSyntax for o
    }
}
```

```cs
IndentiferNameSyntax identifierName = ...;
var typeInfo = semanticModel.GetTypeInfo(identifierName);
```

TypeInfo looks like this:
```
{Microsoft.CodeAnalysis.TypeInfo}
    ConvertedNullability: {Annotation: NotAnnotated, Flow State: NotNull}
    ConvertedType: {object}
    Nullability: {Annotation: NotAnnotated, Flow State: NotNull}
    Type: {object}
```

So we need the sematicModel to get the info. The problem is that we don't have access to the model (yet). There is a "SemanticModel" property on IOperation, but it is null for an IOperation exposed in a cfg. It is still available via `ControlFlowGraph.OriginalOperation.SemanticModel` though so we might gone make it available in the `SymbolicContext`.

I think, sooner or later we will need to adapt S2259 and the engine in general, to also learn from what the compiler knows:

> When the nullable feature is enabled, the compiler will track the flow state of expressions throughout a method, regardless of what the variable was declared as. This flow state will always be represented by the NullableFlowState enum. SemanticModel can be used to request flow state information for individual expressions or sub-expressions through the GetTypeInfo APIs. The TypeInfo struct will be augmented with Nullability and ConvertedNullability information, similar to how it currently has Type and ConvertedType.
[Source](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Nullability%20Public%20API%20Design%20Notes.md#flow-state)

**Comment by pavel-mikula-sonarsource** [comment]
That's a rabbit hole with possible performance implications. Let's do just a simple syntax check in the rule itself to maximize value for a small investment.

**Comment by martin-strecker-sonarsource** [comment]
Replaced by #6091

**Pull request closed without merging**
