### PR TITLE
Fix S1121 FN: Support unsigned right-shift operator (>>>)

### LINKED ISSUE #6308: Fix S1121 FN: Support unsigned right-shift operator (>>>)
### Description

FN for S1121 (AssignmentInsideSubExpression).

Using C#11 unsigned right-shift operator (>>>), the rule is not raising an issue.

### Repro steps

```csharp
void foo(int a) { }

int i = 0;
foo(i >>>= 1); // FN
```

### Expected behavior

The rule should raise an issue.

### Actual behavior

The rule does not raise an issue.

### PR DESCRIPTION
**Pull request by cristian-ambrosini-sonarsource**
Fixes #6308

### CODE REVIEW

**Review by gregory-paidis-sonarsource — APPROVED** [review]

**Comment by csaba-sagi-sonarsource** [comment]
`IsCompliantAssignmentInsideExpression` method can be simplified a lot by merging the `if`s and in the end it will be an expression bodied method.

**Comment by csaba-sagi-sonarsource** [comment]
Also the parameters of `IsInStatementCondition<T>` are not formatted correctly. Check [here](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/coding-style.md#multi-line-statements) how they should be formatted.

**Review by csaba-sagi-sonarsource — CHANGES_REQUESTED** [review]
I have left a few cleanup comments.

**Review by csaba-sagi-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
