### PR TITLE
[Do not merge] We should allow CFG build exceptions to find out what syntax we do not support

### LINKED ISSUE #2541: We should allow CFG build exceptions to find out what syntax we do not support
Currently in [CSharpControlFlowGraph.cs ](https://github.com/SonarSource/sonar-dotnet/blob/7.15.0.8572/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraph.cs#L53) we are eating the exceptions we throw during the Control Flow Graph build process.

This means we have hidden errors or syntax we don't support that we may not be aware of.

We should log the stacktrace (on a single line) and enable these failures to catch them during our QA steps.

SonarCsharp version 7.15

### PR DESCRIPTION
**Pull request by alban-auzeill**
Fixes #2541

### CODE REVIEW

**Comment by alban-auzeill** [comment]
This PR helps us highlighting the syntax nodes that are not fully supported by our CFG builder.
The result is:
* DeclarationExpression
* DefaultLiteralExpression
* LocalFunctionStatement
* ForEachVariableStatement
* ThrowExpression
* TupleExpression

But we will not merge it onto master, because:
* The PR is not complete, we need to raise issues only in a `Hard Fail` mode defined by property, like the property `"sonar.security.hardfail"` in sonar-security.
* There's a workaround to avoid throwing exceptions for the above unsupported syntax nodes list. Without this workaround, ITs fails. Removing this workaround means fixing the CFG implementation, and we don't want to fix it in `sonar-dotnet`. Currently, the most up-to-date C# CFG implementation is in `sonar-security`, it's the one that will be extracted as a shared library and later used by `sonar-dotnet`.

**Comment by alban-auzeill** [comment]
ForEachVariableStatement should be fixed by #2675

**Comment by alban-auzeill** [comment]
DefaultLiteralExpression should be fixed by #2678

**Comment by alban-auzeill** [comment]
LocalFunctionStatement should be fixed by #2679

**Comment by alban-auzeill** [comment]
ThrowExpression should be fixed by #2680

**Comment by alban-auzeill** [comment]
TupleExpression should be fixed by #2681

**Comment by andrei-epure-sonarsource** [comment]
currently  #2541 is paused, we can start over from this branch later on

the idea is that we need to factor out the CFG from sonar-security and used it here, so until now it's not worth spending time fixing the issues

**Pull request closed without merging**
