### PR TITLE
Performance: UtilityAnalyzerBase calls GetSemanticModel for each SyntaxTree

### LINKED ISSUE #6558: Performance: UtilityAnalyzerBase calls GetSemanticModel for each SyntaxTree
`UtilityAnalyzerBase` calls `Compilation.GetSematicModel(syntaxTree)` here

https://github.com/SonarSource/sonar-dotnet/blob/f6a6857245b7ae96c7083ddbb8eebf06b30a4054/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs#L98-L100

This is such a big performance issue that the Roslyn team wrote an analyzer [RS1030](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md#rs1030-do-not-invoke-compilationgetsemanticmodel-method-within-a-diagnostic-analyzer) to flag its use. We should consider looking for a better approach as described by the message of that rule:

https://github.com/dotnet/roslyn-analyzers/issues/3114#issuecomment-674199811

### LINKED ISSUE #7368: UtilityAnalyzer: Roll back the reversal of #6576 and bring back RegisterSemanticModelAction
#6576 added support for `RegisterSemanticModelAction`. The Roslyn compiler pipeline exposes several entry points into the compilation pipeline. RegisterSemanticModelAction is one of them and currently missing. #6576 was rolled back by #7262 (reasoning can be found there). The part of #6576 that added the registration including the tests should be added back to the code base. The registration of the UtilityAnalyzer should be changed to use RegisterSemanticModelAction to re-use the semantic model but only after all UtilityAnalyzer are re-worked in a way to reduce the queries to the semantic model to the absolute minimum. If this is not possible, some UtilityAnalyzer (like e.g. the symref analyzer) might opt to create there own semantic model.

### PR DESCRIPTION
**Pull request by martin-strecker-sonarsource**
Fixes #6558
Fixes #7368

See https://github.com/SonarSource/sonar-dotnet/issues/7368#issuecomment-1618104968 for the acceptance criteria.

### CODE REVIEW

**Comment by martin-strecker-sonarsource** [comment]
Akka

Before (master c8facab6d477f0e749533193dce80e005d0c11b4)

00:01:24.06
00:01:29.60
00:01:32.86

After

00:01:14.65
00:01:17.13
00:01:25.65

**Review by sebastien-marichal — APPROVED** [review]
LGTM!

**Comment by andrei-epure-sonarsource** [comment]
@martin-strecker-sonarsource it would be interesting to see before and after on bigger projects.

**Comment by martin-strecker-sonarsource** [comment]
@costin-zaharia-sonarsource and I agreed on acceptance criteria previously. They are described here:
https://github.com/SonarSource/sonar-dotnet/issues/7368#issuecomment-1618104968
I think we meet those.
We also do a performance comparison for a bigger set of projects for the whole sprint. The results can be found [here](https://docs.google.com/spreadsheets/d/1So6qSOwELpnxVEpXnnEd_KUm5bcvHrTpnKd59rNx2kk/edit?usp=sharing) (internal link).

**Pull request merged**
