### PR TITLE
Fix OWASP links in docs

### PR DESCRIPTION
**Pull request by lolgab**
This PR fixes some links to OWASP website that resulted in 404.

### CODE REVIEW

**Comment by andrei-epure-sonarsource** [comment]
thanks @lolgab , this is really helpful

our rules database is stored on https://jira.sonarsource.com/projects/RSPEC/ so we'll need to do the updates there.

I forwarded this PR internally to speed up the changes we need to do

**Comment by lolgab** [comment]
Thank you very much!

**Comment by andrei-epure-sonarsource** [comment]
The team in charge of the rules repository is aware of the problem of changed links, I will close this PR.

Thanks again for a great contribution!

**Comment by lolgab** [comment]
Thank you for the great tool!

**Pull request closed without merging**
