### PR TITLE
Replace documentation broken link to to coverage page

### LINKED ISSUE #5852: Replace 404 doc link
Old link (generic, now gives 404): https://docs.sonarqube.org/latest/analysis/coverage/
New link (Dotnet): https://docs.sonarqube.org/latest/analysis/test-coverage/dotnet-test-coverage/

### PR DESCRIPTION
**Pull request by andrei-epure-sonarsource**
Fixes #5852

### CODE REVIEW

**Review by martin-strecker-sonarsource — APPROVED** [review]
I can not validate the links. I think these get translated somehow (because non of the links are working for me).

**Comment by andrei-epure-sonarsource** [comment]
@martin-strecker-sonarsource  the links are relative to the sonarqube root

These docs are :
- https://docs.sonarqube.org/latest/analysis/languages/csharp/
- https://docs.sonarqube.org/latest/analysis/languages/vbnet/

You can test there the 404, change based on the PR changes and verify it works

**Comment by martin-strecker-sonarsource** [comment]
I checked the new links (by checking the replacement of an existing link and the new link). It is alright 👍 .

**Comment by martin-strecker-sonarsource** [comment]
LGTM

**Comment by pavel-mikula-sonarsource** [comment]
This card was in ToDo column for some weird reason. I've moved it to `Review approved`

**Comment by andrei-epure-sonarsource** [comment]
maybe when I added the milestone?

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource Noted to investigate.

**Comment by pavel-mikula-sonarsource** [comment]
> to the [8.42](/SonarSource/sonar-dotnet/milestone/97) milestone

The problem was, that this PR fixes an issue. So the issue, that was already on the Kanban, should have been milestoned instead.
Adding milestone added this card to `ToDo`. And that's expected behavior.

**Pull request merged**
