### PR TITLE
S125: Add FP Repro for #8819

### PR DESCRIPTION
**Pull request by antonioaversa**
Repro for https://github.com/SonarSource/sonar-dotnet/issues/8819

### CODE REVIEW

**Review by martin-strecker-sonarsource — APPROVED** [review]
LGTM

**Comment by sonerd** [comment]
Hi @martin-strecker-sonarsource, is there also a fix for JAVA?

Thanks.

**Comment by martin-strecker-sonarsource** [comment]
Hi @sonerd,

Java has it's own implementation of S125 which is not related to ours. Please reach out to the Java team via our [community forum](https://community.sonarsource.com/c/rules-and-languages/fp/7). Thanks

**Comment by sonerd** [comment]
Hi @martin-strecker-sonarsource, 
thanks for the response. 
I have found the related Java issue which seems to be already resolved.
Regards

**Pull request merged**
