### PR TITLE
Add net48 TargetFramework to TestFramework.Test

### PR DESCRIPTION
**Pull request by sebastien-marichal**

### CODE REVIEW

**Review by cristian-ambrosini-sonarsource — APPROVED** [review]
LGTM!

**Comment by pavel-mikula-sonarsource** [comment]
@sebastien-marichal Why was this needed? I don't see any description or reference. And that project didn't have anything specific to .NET Framework AFAICT.

**Comment by sebastien-marichal** [comment]
@pavel-mikula-sonarsource we were missing coverage similar to #8696.
After taking a look at the coverage reports, I saw that the missing branches were missing in the .Net Framework reports. Adding the net48 target framework seemed the easiest path at the moment.

After discussing with @cristian-ambrosini-sonarsource, those changes will be reverted to have better reports and avoid reporting (un)covered branches more than necessary.

**Comment by pavel-mikula-sonarsource** [comment]
Please revert it

**Comment by pavel-mikula-sonarsource** [comment]
Please ping me once it's done, I need to update branch protection rules

**Pull request merged**
