### PR TITLE
S4158: Add FP repro for #7764

### PR DESCRIPTION
**Pull request by cristian-ambrosini-sonarsource**
Add repro for #7764

### CODE REVIEW

**Review by antonioaversa — COMMENTED** [review]
I have left a minor comment.

As discussed, @Tim-Pohlmann should have a look and determine whether the scenario described by the user [here](https://github.com/SonarSource/sonar-dotnet/issues/7764) is really a False Positive or not.

In my opinion the rule is behaving appropriately, because you can always replace `emptySet.UnionWith(something)` with `emptySet = something`, provided that `emptySet` is not a `readonly` field.

Even when you have complex logic, as in the scenario shown by the user, you can simplify the code to a simple assignment, and avoid iteration of the empty `HashSet`.

```cs
var foo1 = new[] { 1, 2 };
var foo2 = new[] { 2, 3 };

bool condition1 = true;
bool condition2 = true;

HashSet<int> set = new();
if (condition1)
{
    set.UnionWith(foo1);
}
if (condition2)
{
    set.UnionWith(foo2);
}
```

becomes

```cs
var foo1 = new[] { 1, 2 };
var foo2 = new[] { 2, 3 };

bool condition1 = true;
bool condition2 = true;

HashSet<int> set;
if (condition1)
{
    set = foo1; // Use assignment, instead of UnionWith
}
if (condition2)
{
    set = foo2; // Use assignment, instead of UnionWith
}
``` 

I tried to use `const` on the local variable, and see if I could break the rule, but I could actually not, since `const` requires true immutability.

**Comment by Tim-Pohlmann** [comment]
This is not an FP. I designed the rule behavior with precisely this case in mind (it showed up a bunch of times on Peachee). We could change the rule if the pattern is very common, but I find it better to just assign a new HashSet instead of the Union on an empty one.

**Comment by cristian-ambrosini-sonarsource** [comment]
> This is not an FP. I designed the rule behavior with precisely this case in mind (it showed up a bunch of times on Peachee). We could change the rule if the pattern is very common, but I find it better to just assign a new HashSet instead of the Union on an empty one.

What do you mean with 

> We could change the rule if the pattern is very common

? That it's a FP or that the rule might be noisy?
In my opinion, this invocation is different than the others because it requires some sort of refactoring. Removing the line will produce a different result, while for other cases removing the line is just the correct thing to do and the results will be functional.

**Comment by Tim-Pohlmann** [comment]
> That it's a FP or that the rule might be noisy?
It's not an FP but an exception could be made if it's a very popular pattern.

**Comment by cristian-ambrosini-sonarsource** [comment]
Based on the discussion above and given the unanimous opinion I'll close this issue as it's not considered a FP.

**Pull request closed without merging**
