### PR TITLE
Support BinaryOperation for Boolean expressions in SE

### LINKED ISSUE #5478: Support BinaryOperation for Boolean expressions in SE
Support basic BinaryOperations when both sides can be resolved to boolean constraints
```
var isTrue = true;
if(isTrue == true)
  // Visit
else
  // Unreachable
```
Operators: ==, !=, =, <>, &&, ||, &, |, AndAlso, OrElse, Xor, ^

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #5478

### CODE REVIEW

**Review by csaba-sagi-sonarsource — APPROVED** [review]
LGTM!  We should also add support for unary operators. Negation is used a lot and would be nice to support. Most probably in a separate PR. Will you open an issue for it?

**Comment by pavel-mikula-sonarsource** [comment]
Negation on booleans does not translate to unary operation, it is already supported by supporting the property CFG shape, see
https://github.com/SonarSource/sonar-dotnet/blob/ab6dfa051830a0370fa16b72d009e8b75f4347a2/analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs#L319-L336

https://github.com/SonarSource/sonar-dotnet/blob/ab6dfa051830a0370fa16b72d009e8b75f4347a2/analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs#L357-L374

and complex case

https://github.com/SonarSource/sonar-dotnet/blob/ab6dfa051830a0370fa16b72d009e8b75f4347a2/analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs#L416-L445

**Comment by csaba-sagi-sonarsource** [comment]
@pavel-mikula-sonarsource  I did not provide an example, my bad... 
I tried the following example, which did not work:
```
var isTrue = true;
var isFalse = false;

if (isTrue == !isFalse)
    Tag(""True"");
else
    Tag(""True Unreachable"");
```

**Comment by pavel-mikula-sonarsource** [comment]
[MMF-2563](https://jira.sonarsource.com/browse/MMF-2563) will be a good place to do stuff like this

**Comment by Tim-Pohlmann** [comment]
The example above works now. It got implemented during an earlier MMF.

**Pull request merged**
