### PR TITLE
Fix S4502 FN: Support generic attributes

### LINKED ISSUE #6314: Fix S4502 FN: Support generic attributes
### Description

FP for [S4502](https://sonarsource.github.io/rspec/#/rspec/S4502/csharp) (DisablingCsrfProtection).

Using generic attributes that inherit from IgnoreAntiforgeryTokenAttribute the rule is not  raising.

### Repro steps

```
    internal class TestCases
    {
        [GenericIgnoreAntiforgeryToken<int>] // FN
        public void A() { }

        public void C() { }
    }
    public class GenericIgnoreAntiforgeryToken<T> : IgnoreAntiforgeryTokenAttribute { }
```

### Expected behavior

The rule should raise

### Actual behavior

The rule is not raising.

### PR DESCRIPTION
**Pull request by gregory-paidis-sonarsource**
Fixes #6314

### CODE REVIEW

**Review by cristian-ambrosini-sonarsource — APPROVED** [review]
LGTM!

**Comment by csaba-sagi-sonarsource** [comment]
> Now properly supports type/attribute inheritance, as well as aliases.
> 
> I also benchmarked the before/after analysis and the times are comparable.
> 
> Before	Total	Analysis	Rule#4502
> Run 1	12.242	3.43088	0
> Run 2	12.501	4.164	0
> Run 3	12.143	3.56761	0
> AVG	12.29533333	3.72083	0
> After	Total	Analysis	Rule#4502
> Run 1	12.513	3.53942	0
> Run 2	11.337	2.2475	0
> Run 3	11.713	3.339	0
> AVG	11.85433333	3.041973333	0
> We should also check if this rule is slower during Peach validation, since now it might reach the Semantic Model faster some times.

For me it is very odd that by removing some syntax level checks and going straight to the semantic model we got an improvement in the times. Could you please choose a big project from peach and check there what the performance impact of this change is?

**Comment by gregory-paidis-sonarsource** [comment]
So, I did another run at [Entity Core](https://github.com/dotnet/efcore), analyzing the entire solution 6-7 times before and after and the results are comparable and slightly better after:

|Before #                                                        |Total            |Analysis                      |Performance        |
|----------------------------------------------------------------|-----------------|------------------------------|-------------------|
|run_0                                                           |117.4847089      |1000.936                      |0.062              |
|run_1                                                           |124.6661621      |1326.444                      |0.102              |
|run_2                                                           |111.5327454      |921.690                       |0.144              |
|run_3                                                           |119.4069131      |1268.276                      |0.084              |
|run_4                                                           |121.2553325      |1327.094                      |0.075              |
|run_5                                                           |115.6844693      |1183.666                      |0.109              |
|Average                                                         |116.0887230979592|1147.4490408163267            |0.09404081632653061|




|After #                                                         |Total            |Analysis                      |Performance        |
|----------------------------------------------------------------|-----------------|------------------------------|-------------------|
|run_0                                                           |111.749863       |1072.469                      |0.104              |
|run_1                                                           |116.8462684      |1240.187                      |0.078              |
|run_2                                                           |82.6498526       |699.210                       |0.032              |
|run_3                                                           |101.394674       |1111.910                      |0.108              |
|run_4                                                           |114.1118262      |1108.674                      |0.053              |
|run_5                                                           |115.3374922      |1190.978                      |0.140              |
|run_6                                                           |111.5014615      |1060.577                      |0.080              |
|Average                                                         |107.6559197      |1069.1435714285714285714285714|0.085              |

I think we could merge this with the change and check again the times on the AWS buckets? 
What do you think @csaba-sagi-sonarsource ?

**Comment by csaba-sagi-sonarsource** [comment]
@costin-zaharia-sonarsource I see you were the one who initially implemented the rule. I am a bit afraid by the impact the changes @gregory-paidis-sonarsource made here might have on the performance of the rule, however the two benchmarks he did indicate the opposite. WDYT should we merge it to master and see what happens on peach?

**Comment by costin-zaharia-sonarsource** [comment]
@csaba-sagi-sonarsource: Indeed. The results look good and I think we should merge it and check the performance from peach results when validating the issue.

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
