### PR TITLE
Drop support of Scanner for MSBuild <= 3.0

### LINKED ISSUE #3526: Drop support of Scanner for MSBuild <= 3.0
Scanner for MSBuild <= 3.0 were generating properties for in-plugin communication between Roslyn analyzer and Java plugin:
```
sonar.cs.roslyn.projectOutPath
sonar.cs.roslyn.reportFilePath
sonar.vbnet.roslyn.projectOutPath
sonar.vbnet.roslyn.reportFilePath
```
These were replaced by new properties in Scanner for MSBuild 4.0 (released in December 2017)
```
sonar.cs.roslyn.projectOutPaths
sonar.cs.roslyn.reportFilePaths
sonar.vbnet.roslyn.projectOutPaths
sonar.vbnet.roslyn.reportFilePaths
```

We drop support of the old properties.

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #3526

### CODE REVIEW

**Comment by pavel-mikula-sonarsource** [comment]
@costin-zaharia-sonarsource This is a draft, because rebase will be needed. Only the last commit `Drop support of Scanner for MSBuild <= 3.0` needs review.

**Comment by costin-zaharia-sonarsource** [comment]
> @costin-zaharia-sonarsource This is a draft, because rebase will be needed. Only the last commit `Drop support of Scanner for MSBuild <= 3.0` needs review.

As far as I can tell this commit needs to be rebased since previous commits have been already moved to master.

**Comment by pavel-mikula-sonarsource** [comment]
@costin-zaharia-sonarsource Correct, rebase was done and it's ready to be reviewed and merged. There were about 10 commits before.

**Review by costin-zaharia-sonarsource — APPROVED** [review]
LGTM!

**Pull request merged**
