### PR TITLE
Performance: Add Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers to our code base

### LINKED ISSUE #7690: Performance: Add Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers to our code base
See the discussion here for the motivation:

https://github.com/SonarSource/sonar-dotnet/pull/7652#discussion_r1275024901

Documentation of the rules
https://github.com/dotnet/roslyn-analyzers/blob/main/src/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.md

The PerformanceSensitive attribute is injected as a source file:
https://github.com/dotnet/roslyn-analyzers/blob/main/src/PerformanceSensitiveAnalyzers/PerformanceSensitiveAnalyzers.md

### PR DESCRIPTION
**Pull request by martin-strecker-sonarsource**
Fixes #7690

From what I can tell, the rules are only activated if the `PerformanceSensitive` attribute is applied (I took a brief look at the implementation and it [seems to be the case](
https://github.com/dotnet/roslyn-analyzers/blob/633ade7a83c2b6918c10035247d93fbe1520463d/src/PerformanceSensitiveAnalyzers/Core/AbstractAllocationAnalyzer.cs#L49)).

The attribute is included via the `Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.targets` targets file in [the nuget package](https://nuget.info/packages/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers/3.3.1)

```xml
  <PropertyGroup>
    <GeneratePerformanceSensitiveAttribute Condition="'$(GeneratePerformanceSensitiveAttribute)' == ''">true</GeneratePerformanceSensitiveAttribute>
    <PerformanceSensitiveAttributePath Condition="'$(PerformanceSensitiveAttributePath)' == ''">$(MSBuildThisFileDirectory)PerformanceSensitiveAttribute$(DefaultLanguageSourceExtension)</PerformanceSensitiveAttributePath>
  </PropertyGroup>

  <ItemGroup Condition="'$(GeneratePerformanceSensitiveAttribute)' == 'true' and Exists($(PerformanceSensitiveAttributePath))">
    <Compile Include="$(PerformanceSensitiveAttributePath)" Visible="false" />
    
    <!-- Make sure the source file is embedded in PDB to support Source Link -->
    <EmbeddedFiles Condition="'$(DebugType)' != 'none'" Include="$(PerformanceSensitiveAttributePath)" />
  </ItemGroup>
```

Look at the code smells in SQ to see the analyzer in action. I left some comments about possible FPs.

### CODE REVIEW

**Comment by costin-zaharia-sonarsource** [comment]
Do you also plan to address the logged warnings?

**Comment by martin-strecker-sonarsource** [comment]
> Do you also plan to address the logged warnings?

This is not possible. The "new" warning are FPs and the capture class/delegate warning can not be avoided. We made the change to access the cwt with "TryGetValue" and only if false "GetValue". This avoids the delegate/capture class allocation in the cache hit case (common case). The delegate free variant  "AddOrUpdate" is only available in .Net core:
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2.addorupdate?view=net-7.0

It's not a big deal as we have a lot of savings even with this implementation:
https://github.com/SonarSource/sonar-dotnet/pull/7664

**Comment by pavel-mikula-sonarsource** [comment]
What does this specific issue mean? I don't understand the message:
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=7736&id=sonaranalyzer-dotnet&open=AYnPVgOOMN2cPQ5Qn5Hg

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM, we can try and see how it works.

**Comment by martin-strecker-sonarsource** [comment]
> What does this specific issue mean? I don't understand the message

This puzzled me as well. It even raises here:
```cs
[PerformanceSensitive("uri")] // HAA0502: Explicit new reference type allocation	
void M() { }
```

I think it is because `[PerformanceSensitive]` "calls" the constructor `PerformanceSensitiveAttribute(string uri)` in a sense. Sounds a lot like an FP to me.

**Comment by martin-strecker-sonarsource** [comment]
> What does this specific issue mean? I don't understand the message

@pavel-mikula-sonarsource I think it is this issue:
https://github.com/dotnet/roslyn-analyzers/issues/6851

**Pull request merged**
